language: node_js
node_js:
- "0.12"

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli
- cd /tmp
- /home/travis/build/appdevdesigns/appdev-gma/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/appdev-gma .
- cd appdev-gma
- npm install mocha chai 
- npm install

script:
- npm test
 
